# Site settings
title: SCSS Compiler in PHP
current_version: v1.11.0
description: >
  SCSS compiler written in PHP
url: https://scssphp.github.io
baseurl: /scssphp
repo_url: https://github.com/scssphp/scssphp

# Build settings
markdown: kramdown
exclude:
- Gemfile
- Gemfile.lock
- Makefile
- composer.lock
- frameworks/
- vendor/

# Github Pages
github: [Repository metadata]
plugins:
# Default gh-pages plugins
- jekyll-commonmark-ghpages
- jekyll-relative-links
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
# Additional plugins
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
optional_front_matter:
  remove_originals: true
readme_index:
  remove_originals: true
  with_frontmatter: true
